return {
	legajax = {
		maxacc = 0.01018,
		maxdec = 0.02037,
		energycost = 23000,
		metalcost = 1450,
		buildpic = "CORGOL.DDS",
		buildtime = 24000,
		canmove = true,
		category = "ALL TANK MOBILE WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 -10 -1",
		collisionvolumescales = "50 50 50",
		collisionvolumetype = "BOX",
		corpse = "DEAD",
		explodeas = "hugeexplosiongeneric",
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		mass = 5001,
		health = 7500,
		maxslope = 12,
		speed = 45,
		maxwaterdepth = 12,
		movementclass = "HTANK4",
		nochasecategory = "VTOL",
		objectname = "Units/CORGOL.s3o",
		script = "Units/CORGOL.cob",
		seismicsignature = 0,
		selfdestructas = "hugeExplosionGenericSelfd",
		sightdistance = 450,
		trackoffset = 8,
		trackstrength = 10,
		tracktype = "corwidetracks",
		trackwidth = 49,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.2,
		turnrate = 200,
		customparams = {
			usebuildinggrounddecal = true,
			buildinggrounddecaltype = "decals/corgol_aoplane.dds",
			buildinggrounddecalsizey = 6,
			buildinggrounddecalsizex = 6,
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalalpha = 0.5,
			unitgroup = 'weapon',
			basename = "base",
			firingceg = "barrelshot-large-impulse",
			kickback = "-2.4",
			model_author = "Mr Bob",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "corvehicles/t2",
			techlevel = 2,
			weapon1turretx = 30,
			weapon1turrety = 40,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -10 -1",
				collisionvolumescales = "50 50 50",
				collisionvolumetype = "BOX",
				damage = 4500,
				featuredead = "HEAP",
				footprintx = 4,
				footprintz = 4,
				height = 20,
				metal = 894,
				object = "Units/corgol_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 3000,
				footprintx = 4,
				footprintz = 4,
				height = 4,
				metal = 378,
				object = "Units/cor4X4C.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-large-impulse",
				[2] = "custom:dust_cloud_dirt",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tcormove",
			},
			select = {
				[1] = "tcorsel",
			},
		},
		weapondefs = {
			impulsecannon = {
				areaofeffect = 200,
				avoidfeature = false,
				burnblow = true,
				burst = 3,
				burstrate = 0.3,
				craterareaofeffect = 200,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.9,
				explosiongenerator = "custom:genericshellexplosion-large-aoe",
				gravityaffected = "true",
				impulseboost = 2.4,
				impulsefactor = 2.0,
				name = "Burst-fire Impulse Cannon",
				noselfdamage = true,
				range = 600,
				reloadtime = 3.5,
				soundhit = "xplomed4",
				soundhitwet = "splslrg",
				soundstart = "cannhvy2",
				separation = 2.0,
				nogap = false,
				size = 3,
				sizeDecay = 0.07,
				stages = 12,
				alphaDecay = 0.10,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 900,
				damage = {
					default = 300,
					subs = 66,
					vtol = 18.3,
				},
			},
			semiauto = {
				accuracy = 50,
				areaofeffect = 25,
				avoidfeature = false,
				burnblow = false,
				burst = 3,
				burstrate = 0.2675,
				craterareaofeffect = 25,
				craterboost = 0,
				cratermult = 0,
				duration = 0.08,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.1,
				firestarter = 0,
				intensity = 0.8,
				impulseboost = 0.5,
				impulsefactor = 1.7,
				name = "Heavy Anti-Unit Machine-Gun",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 3,
				range = 600,
				reloadtime = 0.8,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "minigun3",
				soundstartvolume = 9,
				size = 4,
				sprayangle = 500,
				thickness = 0.6,
				tolerance = 6000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 1200,
				damage = {
					default = 100,
					vtol = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "SEMIAUTO",
				onlytargetcategory = "SURFACE",
				fastautoretargeting = true,
			},
		},
	},
}
