return {
	legdaedalus = {
		maxacc = 0.1242,
		maxdec = 0.8211,
		energycost = 615000,
		metalcost = 29000,
		buildpic = "corkorg.DDS",
		buildtime = 555000,
		canmove = true,
		category = "BOT WEAPON ALL NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE CANBEUW",
		collisionvolumeoffsets = "0 -6 -5",
		collisionvolumescales = "97 160 85",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		explodeas = "korgExplosion",
		footprintx = 5,
		footprintz = 5,
		idleautoheal = 5,
		idletime = 1800,
		mass = 200000,
		health = 149000,
		maxslope = 17,
		speed = 33.6,
		maxwaterdepth = 12,
		movementclass = "VBOT5",
		nochasecategory = "VTOL GROUNDSCOUT",
		objectname = "Units/corkorg.s3o",
		pushresistant = true,
		script = "Units/legdaedalus.cob",
		seismicsignature = 0,
		selfdestructas = "korgExplosionSelfd",
		selfdestructcountdown = 10,
		sightdistance = 845,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 0.7392,
		turnrate = 437,
		upright = true,
		customparams = {
			unitgroup = 'weapon',
			customrange = 590,
			model_author = "FireStorm",
			normaltex = "unittextures/cor_normal.dds",
			paralyzemultiplier = 0,
			subfolder = "corgantry",
			techlevel = 3,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -11 0",
				collisionvolumescales = "96 88 134",
				collisionvolumetype = "box",
				damage = 57600,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 17668,
				object = "Units/corkorg_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 28800,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 15067,
				object = "Units/cor3X3A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "krogok1",
			},
			select = {
				[1] = "krogsel1",
			},
		},
		weapondefs = {
			cleansingrarm = {
				areaofeffect = 50,
				avoidfeature = false,
				avoidfriendly = true,
				beamtime = 1,
				beamttl = 1,
				camerashake = 0.1,
				corethickness = 0.4,
				craterareaofeffect = 120,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.45,
				energypershot = 200,
				explosiongenerator = "custom:genericshellexplosion-medium-beam",
				firestarter = 90,
				firetolerance = 300,
				impulseboost = 0,
				impulsefactor = 0,
				laserflaresize = 6,
				name = "Experimental Cleansing Light",
				noselfdamage = true,
				predictboost = 0.3,
				proximitypriority = 1,
				range = 750,
				reloadtime = 0.9,
				rgbcolor = "1 0.5 0",
				rgbcolor2 = "0.9 1.0 0.5",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "heatray3",
				soundstartvolume = 38,
				soundtrigger = 1,
				thickness = 5.5,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1450,
				damage = {
					default = 1250,
				},
			},
			corkorg_laser = {
				areaofeffect = 50,
				avoidfeature = false,
				avoidfriendly = true,
				beamtime = 1,
				beamttl = 1,
				camerashake = 0.1,
				corethickness = 0.4,
				craterareaofeffect = 120,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.45,
				energypershot = 200,
				explosiongenerator = "custom:genericshellexplosion-medium-beam",
				firestarter = 90,
				firetolerance = 300,
				impulseboost = 0,
				impulsefactor = 0,
				laserflaresize = 6,
				name = "Experimental Cleansing Light",
				noselfdamage = true,
				predictboost = 0.3,
				proximitypriority = 1,
				range = 750,
				reloadtime = 0.9,
				rgbcolor = "1 0.5 0",
				rgbcolor2 = "0.9 1.0 0.5",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "heatray3",
				soundstartvolume = 38,
				soundtrigger = 1,
				thickness = 5.5,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1450,
				damage = {
					default = 1250,
				},
			},
			cleansinglarm = {
				areaofeffect = 50,
				avoidfeature = false,
				avoidfriendly = true,
				beamtime = 1,
				beamttl = 1,
				camerashake = 0.1,
				corethickness = 0.4,
				craterareaofeffect = 120,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.45,
				energypershot = 200,
				explosiongenerator = "custom:genericshellexplosion-medium-beam",
				firestarter = 90,
				firetolerance = 300,
				impulseboost = 0,
				impulsefactor = 0,
				laserflaresize = 6,
				name = "Experimental Cleansing Light",
				noselfdamage = true,
				predictboost = 0.3,
				proximitypriority = 1,
				range = 750,
				reloadtime = 0.9,
				rgbcolor = "1 0.5 0",
				rgbcolor2 = "0.9 1.0 0.5",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "heatray3",
				soundstartvolume = 38,
				soundtrigger = 1,
				thickness = 5.5,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1450,
				damage = {
					default = 1250,
				},
			},
			krogkick = {
				areaofeffect = 192,
				avoidfeature = false,
				camerashake = 1500,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:crusherkrog",
				firestarter = 40,
				impulseboost = 1.5,
				impulsefactor = 1.5,
				name = "KrogCrush",
				noselfdamage = true,
				proximitypriority = 5,
				range = 55,
				reloadtime = 0.2,
				rgbcolor = "0 0 0",
				soundhitwet = "splssml",
				soundstart = "xplosml2",
				thickness = 0,
				tolerance = 9000,
				turnrate = 50000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1650,
				customparams = {
					lups_noshockwave = true,
					nofire = true,
				},
				damage = {
					default = 150,
				},
			},
			krogfootstep = {
				areaofeffect = 172,
				camerashake = 400,
				avoidfeature = false,
				canattackground = false,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0,
				explosiongenerator = "custom:footstep-huge",
				impactonly = 1,
				name = "KrogStep",
				noselfdamage = true,
				range = 0,
				reloadtime = 1.5,
				soundhitwet = "splssml",
				soundhitdry = "korgstep",
				soundhitdryvolume = 18,
				soundhitwetvolume = 16,
				weapontype = "Cannon",
				customparams = {
					noexplosionlight = 1,
					nodecal = true,
				},
				damage = {
					default = 0,
				},
			},
			krogweaponaim = {
				areaofeffect = 0,
				impactonly = 1,
				name = "KrogAim",
				noselfdamage = true,
				soundhitdry = "korgaim",
				soundhitdryvolume = 16,
				weapontype = "Cannon",
				customparams = {
					noexplosionlight = 1,
				},
				damage = {
					default = 0,
				},
			},
			krogweaponrestore = {
				areaofeffect = 0,
				impactonly = 1,
				name = "KrogRestore",
				noselfdamage = true,
				soundhitdry = "korgrestore2",
				soundhitdryvolume = 16,
				weapontype = "Cannon",
				customparams = {
					noexplosionlight = 1,
				},
				damage = {
					default = 0,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "cleansingrarm",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				badtargetcategory = "VTOL GROUNDSCOUT",
				def = "corkorg_LASER",
				onlytargetcategory = "NOTSUB",
			},
			[3] = {
				badtargetcategory = "VTOL",
				def = "cleansinglarm",
				onlytargetcategory = "SURFACE",
			},
			[4] = {
				def = "KROGKICK",
				maindir = "-1.4 -1.5 1",
				maxangledif = 170,
				onlytargetcategory = "NOTSUB",
			},
			[5] = {
				def = "KROGKICK",
				maindir = "1.4 -1.5 1",
				maxangledif = 170,
				onlytargetcategory = "NOTSUB",
			},
			[6] = {
				def = "KROGFOOTSTEP",
			},
			[7] = {
				def = "KROGWEAPONAIM",
			},
			[8] = {
				def = "KROGWEAPONRESTORE",
			},
		},
	},
}
